### ISSUE TITLE
Error handling and notifications

### ISSUE THREAD

**Issue by navaneeth** [varnamproject/varnam-browser-addons#11]
We should handle error and notifications better. When one starts typing, we should notify that we are fetching suggestions. Or if there are any errors in communication. Now people don't know what is happening when they start typing.

**Comment by navaneeth** [comment]
Done for firefox

**Comment by navaneeth** [comment]
@jijeshmohan I quickly tested this. Some observations.
- Progress image is not coming
- Popup gets displayed with the progress image even selected language is 'en'

**Comment by jijeshmohan** [comment]
@navaneeth Progress image was not checkin that cause the problem.
