### ISSUE TITLE
Chrome - IME is not getting activated for the first click on some websites

### ISSUE THREAD

**Issue by navaneeth** [varnamproject/varnam-browser-addons#4]
## To reproduce
- Go to [yahoo.com](http://yahoo.com)
- Click on the search bar and activate IME.
- Type something.  No suggestions will be displayed.
- Activate the IME again and type. You can see suggestions shows up.

**Comment by jijeshmohan** [comment]
Looks like this is OS related problem or browser version problem, I have tested it in yahoo with Chrome v 23 (Mac 10.8.2) and it is working fine.
